# Generated by Django 4.0.6 on 2022-07-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
